apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 800703951115.dkr.ecr.ap-northeast-1.amazonaws.com/demo-frontend
  newName: 800703951115.dkr.ecr.ap-northeast-1.amazonaws.com/demo-frontend
  newTag: 5dbd9094
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
